# Generated by Django 5.2.4 on 2025-07-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0002_artisancategory_artisanskill_artisanprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanprofile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
